title: Plates & Places
description: Recipes, travel stories, and food places I recommend — work in progress.
baseurl: ""
url: "https://platesandplaces.github.io"

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
  travel:
    output: true
    permalink: /travel/:path/
  eats:
    output: true
    permalink: /food-guide/:path/

permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
theme: null
plugins: []
